version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password123
    ports:
      - "5432:5432"
    restart: unless-stopped
    # Add healthcheck
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crm_user -d crm_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    volumes:
      # Fix volume mounting conflicts
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
      - ./media:/app/media:rw
      # Remove conflicting datasets_volume, use host path instead
      - ./data/datasets:/app/data/datasets:rw
    environment:
      - DEBUG=False
      - SECRET_KEY=9ekcaxcw$$nknkl^0d&8%2lx-s2wwlq5g#%+k)y6)*!aspbes+c
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=crm_db
      - DB_USER=crm_user
      - DB_PASSWORD=crm_password123
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - PORT=8083
      # Add database connection timeout settings
      - DB_CONN_MAX_AGE=0
      - DB_CONN_HEALTH_CHECKS=True
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  celery:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sh -c "cd /app/crm_project && celery -A crm_project worker --loglevel=info"
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
      - ./data/datasets:/app/data/datasets:rw
    environment:
      - DEBUG=False
      - SECRET_KEY=9ekcaxcw$$nknkl^0d&8%2lx-s2wwlq5g#%+k)y6)*!aspbes+c
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=crm_db
      - DB_USER=crm_user
      - DB_PASSWORD=crm_password123
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - DB_CONN_MAX_AGE=0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  celery-beat:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sh -c "cd /app/crm_project && celery -A crm_project beat --loglevel=info"
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    environment:
      - DEBUG=False
      - SECRET_KEY=9ekcaxcw$$nknkl^0d&8%2lx-s2wwlq5g#%+k)y6)*!aspbes+c
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=crm_db
      - DB_USER=crm_user
      - DB_PASSWORD=crm_password123
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - DB_CONN_MAX_AGE=0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

volumes:
  postgres_data: