version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_password123
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./media:/app/media
      - datasets_volume:/app/data/datasets
    environment:
      - DEBUG=False
      - SECRET_KEY=9ekcaxcw$$nknkl^0d&8%2lx-s2wwlq5g#%+k)y6)*!aspbes+c
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=crm_db
      - DB_USER=crm_user
      - DB_PASSWORD=crm_password123
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - PORT=8083
    depends_on:
      - db
      - redis
    restart: unless-stopped

  celery:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sh -c "cd /app/crm_project && celery -A crm_project worker --loglevel=info"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - datasets_volume:/app/data/datasets
    environment:
      - DEBUG=False
      - SECRET_KEY=9ekcaxcw$$nknkl^0d&8%2lx-s2wwlq5g#%+k)y6)*!aspbes+c
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=crm_db
      - DB_USER=crm_user
      - DB_PASSWORD=crm_password123
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    restart: unless-stopped

  celery-beat:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sh -c "cd /app/crm_project && celery -A crm_project beat --loglevel=info"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DEBUG=False
      - SECRET_KEY=9ekcaxcw$$nknkl^0d&8%2lx-s2wwlq5g#%+k)y6)*!aspbes+c
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=crm_db
      - DB_USER=crm_user
      - DB_PASSWORD=crm_password123
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
  datasets_volume: