# Generated by Django 4.2.16 on 2026-01-07 06:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_id",
                    models.CharField(
                        help_text="Stripe payment ID", max_length=100, unique=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_refunded",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("currency", models.CharField(max_length=3)),
                (
                    "converted_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("converted_currency", models.CharField(blank=True, max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                            ("pending", "Pending"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("stripe_customer_id", models.CharField(blank=True, max_length=100)),
                (
                    "site",
                    models.CharField(
                        blank=True, help_text="Site/platform", max_length=100
                    ),
                ),
                ("plan_name", models.CharField(blank=True, max_length=100)),
                ("plan_days", models.IntegerField(blank=True, null=True)),
                ("user_name", models.CharField(blank=True, max_length=200)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_date",
                    models.DateTimeField(help_text="When payment was created"),
                ),
                ("refunded_date", models.DateTimeField(blank=True, null=True)),
                (
                    "source_account",
                    models.CharField(
                        blank=True, help_text="CGGE, KI, or KT", max_length=50
                    ),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stripe_payments",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
                "indexes": [
                    models.Index(
                        fields=["stripe_id"], name="crm_stripep_stripe__0fda6d_idx"
                    ),
                    models.Index(
                        fields=["customer_email"], name="crm_stripep_custome_703f62_idx"
                    ),
                    models.Index(
                        fields=["status"], name="crm_stripep_status_4bb75f_idx"
                    ),
                    models.Index(
                        fields=["payment_date"], name="crm_stripep_payment_b15557_idx"
                    ),
                    models.Index(
                        fields=["source_account"], name="crm_stripep_source__cce91c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("customer_created", "Customer Created"),
                            ("customer_updated", "Customer Updated"),
                            ("customer_deleted", "Customer Deleted"),
                            ("email_sent", "Email Sent"),
                            ("whatsapp_sent", "WhatsApp Sent"),
                            ("wechat_sent", "WeChat Sent"),
                            ("enrollment_created", "Enrollment Created"),
                            ("enrollment_updated", "Enrollment Updated"),
                            ("payment_received", "Payment Received"),
                            ("payment_failed", "Payment Failed"),
                            ("payment_refunded", "Payment Refunded"),
                            ("course_created", "Course Created"),
                            ("conference_created", "Conference Created"),
                            ("note_added", "Note Added"),
                            ("import_completed", "Import Completed"),
                            ("export_completed", "Export Completed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional activity data"
                    ),
                ),
                ("performed_by", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="crm.customer",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["activity_type"], name="crm_activit_activit_0b68df_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="crm_activit_created_a78d05_idx"
                    ),
                    models.Index(
                        fields=["customer"], name="crm_activit_custome_e11362_idx"
                    ),
                ],
            },
        ),
    ]
