# Generated by Django 4.2.5 on 2025-07-24 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20250724_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_primary',
            field=models.EmailField(help_text='Primary email address', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
