# Generated by Django 4.2.5 on 2025-07-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_customer_email_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='facebook_profile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='instagram_handle',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='linkedin_profile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='twitter_handle',
        ),
        migrations.AddField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Middle name(s)', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='nickname',
            field=models.CharField(blank=True, help_text='Preferred name or nickname', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='suffix',
            field=models.CharField(blank=True, help_text='Suffix (Jr., Sr., III, etc.)', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='title',
            field=models.CharField(blank=True, help_text='Title (Mr., Ms., Dr., Prof., etc.)', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country_region',
            field=models.CharField(blank=True, choices=[('', 'Select Country/Region'), ('AD', 'Andorra (+376)'), ('AE', 'United Arab Emirates (+971)'), ('AF', 'Afghanistan (+93)'), ('AG', 'Antigua and Barbuda (+1)'), ('AI', 'Anguilla (+1)'), ('AL', 'Albania (+355)'), ('AM', 'Armenia (+374)'), ('AO', 'Angola (+244)'), ('AR', 'Argentina (+54)'), ('AS', 'American Samoa (+1)'), ('AT', 'Austria (+43)'), ('AU', 'Australia (+61)'), ('AW', 'Aruba (+297)'), ('AZ', 'Azerbaijan (+994)'), ('BA', 'Bosnia and Herzegovina (+387)'), ('BB', 'Barbados (+1)'), ('BD', 'Bangladesh (+880)'), ('BE', 'Belgium (+32)'), ('BF', 'Burkina Faso (+226)'), ('BG', 'Bulgaria (+359)'), ('BH', 'Bahrain (+973)'), ('BI', 'Burundi (+257)'), ('BJ', 'Benin (+229)'), ('BM', 'Bermuda (+1)'), ('BN', 'Brunei (+673)'), ('BO', 'Bolivia (+591)'), ('BR', 'Brazil (+55)'), ('BS', 'Bahamas (+1)'), ('BT', 'Bhutan (+975)'), ('BW', 'Botswana (+267)'), ('BY', 'Belarus (+375)'), ('BZ', 'Belize (+501)'), ('CA', 'Canada (+1)'), ('CD', 'Democratic Republic of Congo (+243)'), ('CF', 'Central African Republic (+236)'), ('CG', 'Republic of Congo (+242)'), ('CH', 'Switzerland (+41)'), ('CI', 'Ivory Coast (+225)'), ('CK', 'Cook Islands (+682)'), ('CL', 'Chile (+56)'), ('CM', 'Cameroon (+237)'), ('CN', 'China (+86)'), ('CO', 'Colombia (+57)'), ('CR', 'Costa Rica (+506)'), ('CU', 'Cuba (+53)'), ('CV', 'Cape Verde (+238)'), ('CY', 'Cyprus (+357)'), ('CZ', 'Czech Republic (+420)'), ('DE', 'Germany (+49)'), ('DJ', 'Djibouti (+253)'), ('DK', 'Denmark (+45)'), ('DM', 'Dominica (+1)'), ('DO', 'Dominican Republic (+1)'), ('DZ', 'Algeria (+213)'), ('EC', 'Ecuador (+593)'), ('EE', 'Estonia (+372)'), ('EG', 'Egypt (+20)'), ('EH', 'Western Sahara (+212)'), ('ER', 'Eritrea (+291)'), ('ES', 'Spain (+34)'), ('ET', 'Ethiopia (+251)'), ('FI', 'Finland (+358)'), ('FJ', 'Fiji (+679)'), ('FK', 'Falkland Islands (+500)'), ('FM', 'Micronesia (+691)'), ('FO', 'Faroe Islands (+298)'), ('FR', 'France (+33)'), ('GA', 'Gabon (+241)'), ('GB', 'United Kingdom (+44)'), ('GD', 'Grenada (+1)'), ('GE', 'Georgia (+995)'), ('GF', 'French Guiana (+594)'), ('GG', 'Guernsey (+44)'), ('GH', 'Ghana (+233)'), ('GI', 'Gibraltar (+350)'), ('GL', 'Greenland (+299)'), ('GM', 'Gambia (+220)'), ('GN', 'Guinea (+224)'), ('GP', 'Guadeloupe (+590)'), ('GQ', 'Equatorial Guinea (+240)'), ('GR', 'Greece (+30)'), ('GT', 'Guatemala (+502)'), ('GU', 'Guam (+1)'), ('GW', 'Guinea-Bissau (+245)'), ('GY', 'Guyana (+592)'), ('HK', 'Hong Kong (+852)'), ('HN', 'Honduras (+504)'), ('HR', 'Croatia (+385)'), ('HT', 'Haiti (+509)'), ('HU', 'Hungary (+36)'), ('ID', 'Indonesia (+62)'), ('IE', 'Ireland (+353)'), ('IL', 'Israel (+972)'), ('IM', 'Isle of Man (+44)'), ('IN', 'India (+91)'), ('IO', 'British Indian Ocean Territory (+246)'), ('IQ', 'Iraq (+964)'), ('IR', 'Iran (+98)'), ('IS', 'Iceland (+354)'), ('IT', 'Italy (+39)'), ('JE', 'Jersey (+44)'), ('JM', 'Jamaica (+1)'), ('JO', 'Jordan (+962)'), ('JP', 'Japan (+81)'), ('KE', 'Kenya (+254)'), ('KG', 'Kyrgyzstan (+996)'), ('KH', 'Cambodia (+855)'), ('KI', 'Kiribati (+686)'), ('KM', 'Comoros (+269)'), ('KN', 'Saint Kitts and Nevis (+1)'), ('KP', 'North Korea (+850)'), ('KR', 'South Korea (+82)'), ('KW', 'Kuwait (+965)'), ('KY', 'Cayman Islands (+1)'), ('KZ', 'Kazakhstan (+7)'), ('LA', 'Laos (+856)'), ('LB', 'Lebanon (+961)'), ('LC', 'Saint Lucia (+1)'), ('LI', 'Liechtenstein (+423)'), ('LK', 'Sri Lanka (+94)'), ('LR', 'Liberia (+231)'), ('LS', 'Lesotho (+266)'), ('LT', 'Lithuania (+370)'), ('LU', 'Luxembourg (+352)'), ('LV', 'Latvia (+371)'), ('LY', 'Libya (+218)'), ('MA', 'Morocco (+212)'), ('MC', 'Monaco (+377)'), ('MD', 'Moldova (+373)'), ('ME', 'Montenegro (+382)'), ('MF', 'Saint Martin (+590)'), ('MG', 'Madagascar (+261)'), ('MH', 'Marshall Islands (+692)'), ('MK', 'North Macedonia (+389)'), ('ML', 'Mali (+223)'), ('MM', 'Myanmar (+95)'), ('MN', 'Mongolia (+976)'), ('MO', 'Macao (+853)'), ('MP', 'Northern Mariana Islands (+1)'), ('MQ', 'Martinique (+596)'), ('MR', 'Mauritania (+222)'), ('MS', 'Montserrat (+1)'), ('MT', 'Malta (+356)'), ('MU', 'Mauritius (+230)'), ('MV', 'Maldives (+960)'), ('MW', 'Malawi (+265)'), ('MX', 'Mexico (+52)'), ('MY', 'Malaysia (+60)'), ('MZ', 'Mozambique (+258)'), ('NA', 'Namibia (+264)'), ('NC', 'New Caledonia (+687)'), ('NE', 'Niger (+227)'), ('NF', 'Norfolk Island (+672)'), ('NG', 'Nigeria (+234)'), ('NI', 'Nicaragua (+505)'), ('NL', 'Netherlands (+31)'), ('NO', 'Norway (+47)'), ('NP', 'Nepal (+977)'), ('NR', 'Nauru (+674)'), ('NU', 'Niue (+683)'), ('NZ', 'New Zealand (+64)'), ('OM', 'Oman (+968)'), ('PA', 'Panama (+507)'), ('PE', 'Peru (+51)'), ('PF', 'French Polynesia (+689)'), ('PG', 'Papua New Guinea (+675)'), ('PH', 'Philippines (+63)'), ('PK', 'Pakistan (+92)'), ('PL', 'Poland (+48)'), ('PM', 'Saint Pierre and Miquelon (+508)'), ('PN', 'Pitcairn (+64)'), ('PR', 'Puerto Rico (+1)'), ('PS', 'Palestine (+970)'), ('PT', 'Portugal (+351)'), ('PW', 'Palau (+680)'), ('PY', 'Paraguay (+595)'), ('QA', 'Qatar (+974)'), ('RE', 'Reunion (+262)'), ('RO', 'Romania (+40)'), ('RS', 'Serbia (+381)'), ('RU', 'Russia (+7)'), ('RW', 'Rwanda (+250)'), ('SA', 'Saudi Arabia (+966)'), ('SB', 'Solomon Islands (+677)'), ('SC', 'Seychelles (+248)'), ('SD', 'Sudan (+249)'), ('SE', 'Sweden (+46)'), ('SG', 'Singapore (+65)'), ('SH', 'Saint Helena (+290)'), ('SI', 'Slovenia (+386)'), ('SJ', 'Svalbard and Jan Mayen (+47)'), ('SK', 'Slovakia (+421)'), ('SL', 'Sierra Leone (+232)'), ('SM', 'San Marino (+378)'), ('SN', 'Senegal (+221)'), ('SO', 'Somalia (+252)'), ('SR', 'Suriname (+597)'), ('SS', 'South Sudan (+211)'), ('ST', 'Sao Tome and Principe (+239)'), ('SV', 'El Salvador (+503)'), ('SX', 'Sint Maarten (+1)'), ('SY', 'Syria (+963)'), ('SZ', 'Eswatini (+268)'), ('TC', 'Turks and Caicos Islands (+1)'), ('TD', 'Chad (+235)'), ('TF', 'French Southern Territories (+262)'), ('TG', 'Togo (+228)'), ('TH', 'Thailand (+66)'), ('TJ', 'Tajikistan (+992)'), ('TK', 'Tokelau (+690)'), ('TL', 'Timor-Leste (+670)'), ('TM', 'Turkmenistan (+993)'), ('TN', 'Tunisia (+216)'), ('TO', 'Tonga (+676)'), ('TR', 'Turkey (+90)'), ('TT', 'Trinidad and Tobago (+1)'), ('TV', 'Tuvalu (+688)'), ('TW', 'Taiwan (+886)'), ('TZ', 'Tanzania (+255)'), ('UA', 'Ukraine (+380)'), ('UG', 'Uganda (+256)'), ('UM', 'United States Minor Outlying Islands (+1)'), ('US', 'United States (+1)'), ('UY', 'Uruguay (+598)'), ('UZ', 'Uzbekistan (+998)'), ('VA', 'Vatican City (+39)'), ('VC', 'Saint Vincent and the Grenadines (+1)'), ('VE', 'Venezuela (+58)'), ('VG', 'British Virgin Islands (+1)'), ('VI', 'US Virgin Islands (+1)'), ('VN', 'Vietnam (+84)'), ('VU', 'Vanuatu (+678)'), ('WF', 'Wallis and Futuna (+681)'), ('WS', 'Samoa (+685)'), ('YE', 'Yemen (+967)'), ('YT', 'Mayotte (+262)'), ('ZA', 'South Africa (+27)'), ('ZM', 'Zambia (+260)'), ('ZW', 'Zimbabwe (+263)')], help_text='Country/Region', max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fax',
            field=models.CharField(blank=True, help_text='Fax number', max_length=25),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(help_text='First/Given name', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(help_text='Last/Family name', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_primary',
            field=models.CharField(blank=True, help_text='Primary phone number (will auto-add country code)', max_length=25),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_secondary',
            field=models.CharField(blank=True, help_text='Secondary phone number', max_length=25),
        ),
        migrations.AlterField(
            model_name='customer',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number', max_length=25),
        ),
    ]
