# Generated by Django 4.2.5 on 2025-07-24 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_customer_facebook_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='suffix',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='title',
        ),
        migrations.AddField(
            model_name='customer',
            name='facebook_profile',
            field=models.URLField(blank=True, help_text='Facebook profile URL', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='customer',
            name='fax_country_code',
            field=models.CharField(blank=True, help_text='Country code for fax', max_length=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='instagram_handle',
            field=models.CharField(blank=True, help_text='Instagram handle (without @)', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='linkedin_profile',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL', validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='customer',
            name='name_suffix',
            field=models.CharField(blank=True, help_text='Jr., Sr., III, etc.', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_primary_country_code',
            field=models.CharField(blank=True, help_text='Country code for primary phone', max_length=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_secondary_country_code',
            field=models.CharField(blank=True, help_text='Country code for secondary phone', max_length=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_name',
            field=models.CharField(blank=True, help_text='Nickname or preferred name', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='Twitter/X handle (without @)', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_country_code',
            field=models.CharField(blank=True, help_text='Country code for WhatsApp', max_length=5),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country_region',
            field=models.CharField(blank=True, choices=[('', 'Select Country/Region'), ('CN', 'China'), ('HK', 'Hong Kong SAR'), ('TW', 'Taiwan'), ('MO', 'Macau SAR'), ('SG', 'Singapore'), ('MY', 'Malaysia'), ('TH', 'Thailand'), ('VN', 'Vietnam'), ('PH', 'Philippines'), ('ID', 'Indonesia'), ('KR', 'South Korea'), ('JP', 'Japan'), ('IN', 'India'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('GB', 'United Kingdom'), ('DE', 'Germany'), ('FR', 'France'), ('IT', 'Italy'), ('ES', 'Spain'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('CH', 'Switzerland'), ('AT', 'Austria'), ('SE', 'Sweden'), ('NO', 'Norway'), ('DK', 'Denmark'), ('FI', 'Finland'), ('US', 'United States'), ('CA', 'Canada'), ('MX', 'Mexico'), ('BR', 'Brazil'), ('AR', 'Argentina'), ('CL', 'Chile'), ('CO', 'Colombia'), ('PE', 'Peru'), ('AE', 'United Arab Emirates'), ('SA', 'Saudi Arabia'), ('IL', 'Israel'), ('ZA', 'South Africa'), ('EG', 'Egypt'), ('KE', 'Kenya'), ('NG', 'Nigeria'), ('RU', 'Russia'), ('TR', 'Turkey'), ('OTHER', 'Other (please specify in notes)')], help_text='Select your country or region', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fax',
            field=models.CharField(blank=True, help_text='Fax number', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(help_text='Given name/First name', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(help_text='Family name/Last name/Surname', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_primary',
            field=models.CharField(blank=True, help_text='Primary phone number with country code', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_secondary',
            field=models.CharField(blank=True, help_text='Secondary phone number with country code', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
