# Generated by Django 4.2.23 on 2025-07-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_add_address_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='data_processing_consent',
            field=models.BooleanField(default=True, help_text='Consent to data processing'),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='education_level',
            field=models.CharField(blank=True, help_text='Highest education level', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='emergency_contact_email',
            field=models.EmailField(blank=True, help_text='Emergency contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Emergency contact full name', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Emergency contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, help_text='Relationship to emergency contact', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], help_text='Gender', max_length=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal notes (not visible to customer)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='maiden_name',
            field=models.CharField(blank=True, help_text='Maiden name (if applicable)', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='nationality',
            field=models.CharField(blank=True, help_text='Nationality', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='newsletter_subscription',
            field=models.BooleanField(default=False, help_text='Subscribe to newsletter'),
        ),
        migrations.AddField(
            model_name='customer',
            name='other_names',
            field=models.CharField(blank=True, help_text='Other names, aliases, or previous names', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_communication_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('wechat', 'WeChat'), ('sms', 'SMS')], default='email', help_text='Preferred method of communication', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='profession',
            field=models.CharField(blank=True, help_text='Current profession/occupation', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='referral_source',
            field=models.CharField(blank=True, help_text='Referral source if applicable', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(blank=True, help_text='How customer found us', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='special_requirements',
            field=models.TextField(blank=True, help_text='Special requirements or accommodations'),
        ),
        migrations.AddField(
            model_name='customer',
            name='title',
            field=models.CharField(blank=True, help_text='Title (Dr., Prof., Mr., Ms., etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, help_text='Years of professional experience', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='marketing_consent',
            field=models.BooleanField(default=False, help_text='Consent to receive marketing communications'),
        ),
    ]
