# Generated by Django 4.2.16 on 2025-07-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0008_add_enhanced_customer_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="designation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select Designation"),
                    ("professor", "Professor"),
                    ("prof", "Prof."),
                    ("dr", "Dr."),
                    ("phd", "Ph.D."),
                    ("doctorate", "Doctorate"),
                    ("professor_emeritus", "Professor Emeritus"),
                    ("associate_professor", "Associate Professor"),
                    ("assistant_professor", "Assistant Professor"),
                    ("lecturer", "Lecturer"),
                    ("senior_lecturer", "Senior Lecturer"),
                    ("ir", "Ir."),
                    ("eng", "Eng."),
                    ("pe", "P.E."),
                    ("eit", "E.I.T."),
                    ("md", "M.D."),
                    ("do", "D.O."),
                    ("dds", "D.D.S."),
                    ("dvm", "D.V.M."),
                    ("jd", "J.D."),
                    ("esquire", "Esq."),
                    ("cpa", "C.P.A."),
                    ("cfa", "C.F.A."),
                    ("pmp", "P.M.P."),
                    ("mba", "M.B.A."),
                    ("rev", "Rev."),
                    ("father", "Father"),
                    ("pastor", "Pastor"),
                    ("captain", "Captain"),
                    ("colonel", "Colonel"),
                    ("major", "Major"),
                    ("general", "General"),
                    ("other", "Other"),
                ],
                help_text="Professional or academic designation",
                max_length=50,
            ),
        ),
    ]
