# Generated by Django 4.2.16 on 2025-07-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0010_alter_customer_country_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select Source"),
                    ("website", "Website"),
                    ("google_search", "Google Search"),
                    ("social_media", "Social Media"),
                    ("facebook", "Facebook"),
                    ("linkedin", "LinkedIn"),
                    ("instagram", "Instagram"),
                    ("twitter", "Twitter/X"),
                    ("youtube", "YouTube"),
                    ("email_marketing", "Email Marketing"),
                    ("google_ads", "Google Ads"),
                    ("facebook_ads", "Facebook Ads"),
                    ("online_ad", "Online Advertisement"),
                    ("print_ad", "Print Advertisement"),
                    ("radio", "Radio"),
                    ("tv", "Television"),
                    ("billboard", "Billboard"),
                    ("flyer", "Flyer/Brochure"),
                    ("referral", "Referral"),
                    ("word_of_mouth", "Word of Mouth"),
                    ("existing_customer", "Existing Customer"),
                    ("partner", "Partner/Affiliate"),
                    ("employee", "Employee Referral"),
                    ("conference", "Conference/Event"),
                    ("workshop", "Workshop"),
                    ("webinar", "Webinar"),
                    ("trade_show", "Trade Show"),
                    ("seminar", "Seminar"),
                    ("cold_call", "Cold Call"),
                    ("cold_email", "Cold Email"),
                    ("csv_import", "CSV Import"),
                    ("data_migration", "Data Migration"),
                    ("api_import", "API Import"),
                    ("bulk_upload", "Bulk Upload"),
                    ("walk_in", "Walk-in"),
                    ("phone_inquiry", "Phone Inquiry"),
                    ("email_inquiry", "Email Inquiry"),
                    ("contact_form", "Contact Form"),
                    ("other", "Other"),
                    ("unknown", "Unknown"),
                ],
                help_text="How customer found us",
                max_length=100,
            ),
        ),
    ]
