# Generated by Django 4.2.16 on 2025-07-30 07:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0011_alter_customer_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(
                blank=True, help_text="Given name/First name (optional)", max_length=100
            ),
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name for internal reference", max_length=200
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome Email"),
                            ("course_reminder", "Course Reminder"),
                            ("enrollment_confirmation", "Enrollment Confirmation"),
                            ("payment_confirmation", "Payment Confirmation"),
                            ("newsletter", "Newsletter"),
                            ("marketing", "Marketing Email"),
                            ("event_invitation", "Event Invitation"),
                            ("follow_up", "Follow-up Email"),
                            ("survey", "Survey Request"),
                            ("birthday", "Birthday Wishes"),
                            ("custom", "Custom Template"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Email subject line (supports variables)",
                        max_length=200,
                    ),
                ),
                (
                    "content_text",
                    models.TextField(
                        help_text="Plain text content (supports variables)"
                    ),
                ),
                (
                    "content_html",
                    models.TextField(
                        blank=True, help_text="HTML content (supports variables)"
                    ),
                ),
                (
                    "available_variables",
                    models.TextField(
                        blank=True,
                        help_text="Available template variables (JSON format): {{first_name}}, {{course_title}}, etc.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.CharField(
                        blank=True,
                        help_text="Who created this template",
                        max_length=100,
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many times this template has been used",
                    ),
                ),
                ("last_used", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["template_type", "status"],
                        name="crm_emailte_templat_ddf053_idx",
                    ),
                    models.Index(
                        fields=["status", "-updated_at"],
                        name="crm_emailte_status_44f69a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("subject", models.CharField(max_length=200)),
                ("content_text", models.TextField()),
                ("content_html", models.TextField(blank=True)),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all_customers", "All Customers"),
                            ("active_customers", "Active Customers"),
                            ("prospects", "Prospects"),
                            ("students", "Students"),
                            ("corporate_clients", "Corporate Clients"),
                            ("newsletter_subscribers", "Newsletter Subscribers"),
                            ("marketing_consent", "Marketing Consent Given"),
                            ("custom_filter", "Custom Filter"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "custom_filter",
                    models.JSONField(
                        blank=True,
                        help_text="Custom filter criteria in JSON format",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("paused", "Paused"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("total_recipients", models.PositiveIntegerField(default=0)),
                ("emails_sent", models.PositiveIntegerField(default=0)),
                ("emails_delivered", models.PositiveIntegerField(default=0)),
                ("emails_opened", models.PositiveIntegerField(default=0)),
                ("emails_clicked", models.PositiveIntegerField(default=0)),
                ("emails_bounced", models.PositiveIntegerField(default=0)),
                ("emails_failed", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.CharField(blank=True, max_length=100)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.emailtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subscription_type",
                    models.CharField(
                        choices=[
                            ("newsletter", "Newsletter"),
                            ("marketing", "Marketing Emails"),
                            ("course_updates", "Course Updates"),
                            ("event_notifications", "Event Notifications"),
                            ("system_notifications", "System Notifications"),
                        ],
                        max_length=30,
                    ),
                ),
                ("is_subscribed", models.BooleanField(default=True)),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribe_reason", models.CharField(blank=True, max_length=200)),
                (
                    "unsubscribe_token",
                    models.CharField(blank=True, max_length=64, unique=True),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.customer"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["customer", "is_subscribed"],
                        name="crm_emailsu_custome_b6404d_idx",
                    ),
                    models.Index(
                        fields=["subscription_type", "is_subscribed"],
                        name="crm_emailsu_subscri_80cb5d_idx",
                    ),
                ],
                "unique_together": {("customer", "subscription_type")},
            },
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("recipient_email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("content_text", models.TextField()),
                ("content_html", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("failed", "Failed"),
                            ("unsubscribed", "Unsubscribed"),
                            ("complained", "Spam Complaint"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("external_message_id", models.CharField(blank=True, max_length=200)),
                ("queued_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("bounced_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="IP address for opens/clicks", null=True
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True, help_text="User agent for opens/clicks"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.emailcampaign",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.customer"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.emailtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-queued_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "-queued_at"],
                        name="crm_emaillo_custome_6ebe9b_idx",
                    ),
                    models.Index(
                        fields=["campaign", "status"],
                        name="crm_emaillo_campaig_5793bd_idx",
                    ),
                    models.Index(
                        fields=["status", "-queued_at"],
                        name="crm_emaillo_status_5547d7_idx",
                    ),
                    models.Index(
                        fields=["recipient_email", "-queued_at"],
                        name="crm_emaillo_recipie_b111fd_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="emailcampaign",
            index=models.Index(
                fields=["status", "-created_at"], name="crm_emailca_status_02c6c3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailcampaign",
            index=models.Index(
                fields=["target_audience", "status"],
                name="crm_emailca_target__725218_idx",
            ),
        ),
    ]
