# Generated by Django 4.2.16 on 2025-07-31 07:54

from django.db import migrations, models
from django.core.validators import URLValidator


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0012_alter_customer_first_name_emailtemplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='youtube_handle',
            field=models.CharField(blank=True, help_text='YouTube handle (without @)', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='youtube_channel_url',
            field=models.URLField(blank=True, help_text='Full YouTube channel URL', validators=[URLValidator()]),
        ),
    ]
