# Generated by Django 4.2.16 on 2025-08-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0017_add_performance_indexes"),
    ]

    operations = [
        # Fix youtube_handle field to allow NULL values
        migrations.AlterField(
            model_name='customer',
            name='youtube_handle',
            field=models.CharField(max_length=100, blank=True, null=True, help_text="YouTube handle (without @)"),
        ),
    ]
