# Generated by Django 4.2.16 on 2025-08-07 06:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0018_auto_20250807_0655"),
    ]

    operations = [
        # Direct SQL to alter youtube_handle to allow NULL values
        migrations.RunSQL(
            "UPDATE crm_customer SET youtube_handle = NULL WHERE youtube_handle = '';",
            reverse_sql="UPDATE crm_customer SET youtube_handle = '' WHERE youtube_handle IS NULL;"
        ),
        migrations.RunSQL(
            "CREATE TABLE crm_customer_new AS SELECT * FROM crm_customer;",
            reverse_sql="DROP TABLE crm_customer_new;"
        ),
        migrations.RunSQL(
            "DROP TABLE crm_customer;",
            reverse_sql="CREATE TABLE crm_customer AS SELECT * FROM crm_customer_new;"
        ),
        migrations.RunSQL(
            '''CREATE TABLE "crm_customer" (
                "id" char(32) NOT NULL PRIMARY KEY, 
                "first_name" varchar(100) NOT NULL, 
                "last_name" varchar(100) NOT NULL, 
                "whatsapp_number" varchar(20) NOT NULL, 
                "wechat_id" varchar(100) NOT NULL, 
                "customer_type" varchar(20) NOT NULL, 
                "status" varchar(20) NOT NULL, 
                "preferred_learning_format" varchar(50) NOT NULL, 
                "interests" text NOT NULL, 
                "marketing_consent" bool NOT NULL, 
                "created_at" datetime NOT NULL, 
                "updated_at" datetime NOT NULL, 
                "email_secondary" varchar(254) NOT NULL, 
                "phone_primary" varchar(20) NOT NULL, 
                "phone_secondary" varchar(20) NOT NULL, 
                "fax" varchar(20) NOT NULL, 
                "country_region" varchar(10) NOT NULL, 
                "company_primary" varchar(200) NOT NULL, 
                "position_primary" varchar(100) NOT NULL, 
                "company_secondary" varchar(200) NOT NULL, 
                "position_secondary" varchar(100) NOT NULL, 
                "company_website" varchar(200) NOT NULL, 
                "address_primary" text NOT NULL, 
                "address_secondary" text NOT NULL, 
                "middle_name" varchar(100) NOT NULL, 
                "facebook_profile" varchar(200) NOT NULL, 
                "fax_country_code" varchar(5) NOT NULL, 
                "instagram_handle" varchar(100) NOT NULL, 
                "linkedin_profile" varchar(200) NOT NULL, 
                "name_suffix" varchar(20) NOT NULL, 
                "phone_primary_country_code" varchar(5) NOT NULL, 
                "phone_secondary_country_code" varchar(5) NOT NULL, 
                "preferred_name" varchar(100) NOT NULL, 
                "twitter_handle" varchar(100) NOT NULL, 
                "whatsapp_country_code" varchar(5) NOT NULL, 
                "city" varchar(100) NOT NULL, 
                "postal_code" varchar(20) NOT NULL, 
                "state_province" varchar(100) NOT NULL, 
                "address" varchar(500) NOT NULL, 
                "data_processing_consent" bool NOT NULL, 
                "date_of_birth" date NULL, 
                "education_level" varchar(100) NOT NULL, 
                "emergency_contact_email" varchar(254) NOT NULL, 
                "emergency_contact_name" varchar(200) NOT NULL, 
                "emergency_contact_phone" varchar(20) NOT NULL, 
                "emergency_contact_relationship" varchar(100) NOT NULL, 
                "gender" varchar(1) NOT NULL, 
                "internal_notes" text NOT NULL, 
                "maiden_name" varchar(100) NOT NULL, 
                "nationality" varchar(100) NOT NULL, 
                "newsletter_subscription" bool NOT NULL, 
                "other_names" varchar(200) NOT NULL, 
                "preferred_communication_method" varchar(20) NOT NULL, 
                "profession" varchar(100) NOT NULL, 
                "referral_source" varchar(100) NOT NULL, 
                "source" varchar(100) NOT NULL, 
                "special_requirements" text NOT NULL, 
                "title" varchar(50) NOT NULL, 
                "years_of_experience" integer unsigned NULL CHECK ("years_of_experience" >= 0), 
                "designation" varchar(50) NOT NULL, 
                "youtube_handle" varchar(100) NULL, 
                "youtube_channel_url" varchar(200) NOT NULL, 
                "email_primary" varchar(254) NULL
            );''',
            reverse_sql="DROP TABLE crm_customer;"
        ),
        migrations.RunSQL(
            "INSERT INTO crm_customer SELECT * FROM crm_customer_new;",
            reverse_sql="DELETE FROM crm_customer;"
        ),
        migrations.RunSQL(
            "DROP TABLE crm_customer_new;",
            reverse_sql="CREATE TABLE crm_customer_new AS SELECT * FROM crm_customer;"
        ),
        # Recreate indexes
        migrations.RunSQL(
            '''CREATE INDEX IF NOT EXISTS crm_customer_email_primary_idx ON crm_customer(email_primary);
               CREATE INDEX IF NOT EXISTS crm_customer_type_status_idx ON crm_customer(customer_type, status);
               CREATE INDEX IF NOT EXISTS crm_customer_country_region_idx ON crm_customer(country_region);
               CREATE INDEX IF NOT EXISTS crm_customer_source_idx ON crm_customer(source);
               CREATE INDEX IF NOT EXISTS crm_customer_phone_primary_idx ON crm_customer(phone_primary);
               CREATE INDEX IF NOT EXISTS crm_customer_whatsapp_idx ON crm_customer(whatsapp_number);
               CREATE INDEX IF NOT EXISTS crm_customer_youtube_handle_idx ON crm_customer(youtube_handle);
               CREATE INDEX IF NOT EXISTS crm_customer_created_status_idx ON crm_customer(created_at, status);''',
            reverse_sql="DROP INDEX IF EXISTS crm_customer_email_primary_idx; DROP INDEX IF EXISTS crm_customer_type_status_idx; DROP INDEX IF EXISTS crm_customer_country_region_idx; DROP INDEX IF EXISTS crm_customer_source_idx; DROP INDEX IF EXISTS crm_customer_phone_primary_idx; DROP INDEX IF EXISTS crm_customer_whatsapp_idx; DROP INDEX IF EXISTS crm_customer_youtube_handle_idx; DROP INDEX IF EXISTS crm_customer_created_status_idx;"
        ),
    ]
