# Generated by Django 4.2.7 on 2025-08-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0019_auto_20250807_0659"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="communicationlog",
            index=models.Index(
                fields=["customer", "channel"], name="crm_communi_custome_d81612_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communicationlog",
            index=models.Index(
                fields=["sent_at"], name="crm_communi_sent_at_fd66af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communicationlog",
            index=models.Index(
                fields=["is_outbound"], name="crm_communi_is_outb_8ca42e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="communicationlog",
            index=models.Index(
                fields=["channel", "sent_at"], name="crm_communi_channel_7f3e95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conference",
            index=models.Index(
                fields=["is_active", "start_date"],
                name="crm_confere_is_acti_9b60d6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conference",
            index=models.Index(
                fields=["start_date"], name="crm_confere_start_d_41bc3b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conference",
            index=models.Index(
                fields=["created_at"], name="crm_confere_created_da6f45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferenceregistration",
            index=models.Index(
                fields=["customer"], name="crm_confere_custome_77e2d6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferenceregistration",
            index=models.Index(
                fields=["conference"], name="crm_confere_confere_3c4bfc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conferenceregistration",
            index=models.Index(
                fields=["registration_date"], name="crm_confere_registr_dab327_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["course_type", "is_active"],
                name="crm_course_course__1849a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["start_date"], name="crm_course_start_d_8a2490_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["registration_deadline"], name="crm_course_registr_a5fc09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["is_active", "start_date"], name="crm_course_is_acti_bc68f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["email_primary"], name="crm_custome_email_p_e2a267_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["customer_type", "status"],
                name="crm_custome_custome_22ad63_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["country_region"], name="crm_custome_country_6b36a7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["source"], name="crm_custome_source_5f98c6_idx"),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["marketing_consent"], name="crm_custome_marketi_8dc72f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["phone_primary"], name="crm_custome_phone_p_4563f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["whatsapp_number"], name="crm_custome_whatsap_374cb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["youtube_handle"], name="crm_custome_youtube_07ed9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["created_at", "status"], name="crm_custome_created_739a98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["customer_type", "created_at"],
                name="crm_custome_custome_48c3d1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["customer", "status"], name="crm_enrollm_custome_15b5ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["course", "status"], name="crm_enrollm_course__f35f20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["enrollment_date"], name="crm_enrollm_enrollm_f946e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["payment_status"], name="crm_enrollm_payment_64b8f3_idx"
            ),
        ),
    ]
